spring:
  datasource:
    url: jdbc:mysql://192.168.1.235:3306/oss_server?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456

upload:
  local:
    basePath: F:/save/
    tmpsave: F:/save/temp/    