server:
  port: 9100
  servlet:
    session:
      timeout: 120s
  
spring:
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 200MB
      
  datasource:
    url: jdbc:mysql://192.168.1.235:3306/oss_server?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    #driver-class-name: com.mysql.jdbc.Driver
  
upload:
  local:
    basePath: F:/save/
    tmpsave: F:/save/temp/
  oss:
    test: yctest/test/
    online: yctest/online/
  qrCode: 
    basePath: F:/qrCode/
mybatis:
  type-aliases-package: com.llmj.oss.model
  #mapper-locations: classpath:mybatis-mappers/*Mapper.xml 
    
logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/admin-oss.log
  maxsize: 30MB
  maxhistory: 168