server:
  port: 9100
  servlet:
    session:
      timeout: 11120s
  
spring:
  profiles:
    active: 154
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 200MB      
    
mybatis:
  type-aliases-package: com.llmj.oss.model
  #mapper-locations: classpath:mybatis-mappers/*Mapper.xml 
    
logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/admin-oss.log
  maxsize: 30MB
  maxhistory: 168