spring:
  datasource:
    url: jdbc:mysql://192.168.1.235:3306/oss_server?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  
  rabbitmq:
    host: 192.168.1.154
    port: 5672
    username: MyTest1
    password: 123456
    publisher-confirms: true
    virtual-host: /
    
upload:
  local:
    basePath: F:/save/
    tmpsave: F:/save/temp/   
    qrcode: F:/save/qrcode/ 