spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:31036/oss_server?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Psg1j!ODYPk99UPc

upload:
  local:
    basePath: /data/llmj_sp/oss_web/save/
    tmpsave: /data/llmj_sp/oss_web/save/temp/  