spring:
  datasource:
    url: jdbc:mysql://172.21.0.97:3306/oss_server?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: llmj_supp
    password: Ukve2qv4apwkS
  
  rabbitmq:
    host: 172.21.0.97
    port: 5672
    username: shuabao
    password: infUJ04n
    publisher-confirms: true
    virtual-host: /
    
  redis:
    host: 172.21.0.97
    port: 6379
    timeout: 1000
    password: j7xlHKNfu
    database: 0
    pool:
      max-active: 20
      max-idle: 20
      max-wait: 1000 
  
upload:
  local:
    basePath: /data/llmj_sp/oss_web/save/
    tmpsave: /data/llmj_sp/oss_web/save/temp/
    qrcode: /data/llmj_sp/oss_web/save/qrcode/